language: ruby
gemfile:
- gemfiles/travis.gemfile
rvm:
- 1.9.3
env:
  global:
  matrix:
  - KITCHEN_INSTANCE='default-ubuntu-1204'
  - KITCHEN_INSTANCE='default-ubuntu-1004'
  - KITCHEN_INSTANCE='default-centos-64'
  - KITCHEN_INSTANCE='default-centos-53'
  - KITCHEN_INSTANCE='deploy-libs-ubuntu-1204'
  - KITCHEN_INSTANCE='deploy-libs-ubuntu-1004'
  - KITCHEN_INSTANCE='deploy-libs-centos-64'
  - KITCHEN_INSTANCE='deploy-libs-centos-53'
  - KITCHEN_INSTANCE='deploy-war-ubuntu-1204'
  - KITCHEN_INSTANCE='deploy-war-ubuntu-1004'
  - KITCHEN_INSTANCE='deploy-war-centos-64'
  - KITCHEN_INSTANCE='deploy-war-centos-53'
script: 
  - bundle exec kitchen test $KITCHEN_INSTANCE 
after_script:
  - bundle exec kitchen destroy
notifications:
  email:
  - abutovich@qubell.com

