language: ruby
gemfile:
- Gemfile
rvm:
- 1.9.3
before_install:
- echo -n $EC2_KEY_CHUNK_{0..32} >> ~/.ssh/id_ec2.base64
- cat ~/.ssh/id_ec2.base64 | tr -d ' ' | base64 --decode > ~/.ssh/id_ec2.pem
env:
  global:
  - secure: Iex9nApP1unmW++fCS+f/pMKDTcSYzjcR0K+r+mtJ8sZjiRC5TnxCScbN2GXYly92VOuA0Khi5NnIgUrXSWGd4bFhtHMLyPEOcJzOHd25spWL3cf9rFKKypsz4kc3afikGZLgPChFbnrA0AwvcjiPx0bhcl1JHYHIwCzJlX0lFU=
  - secure: K1si0SKxMLXPXPeicbs5zke/7WYkdH5P5NZj4MqSESpUx+JbQL/pnNzm1D0cFyZsu5K/qb4a9ydgL/zIQ0843KK7P1GRz9pdjmlqIaKA8IiufPufSkyGbV0c4KK/BTshe83L8cYrqqWS09jqHlY8f8+MxxNsS12v35X5jOlRbpk=
  - secure: Ct00fpU3+riZGobo9RsMneLIHSyPK7hSGTsMNNnbNvIgS2PzhA7xe03TRhIfGTFEQ+TagLsN8sIGMy2PwE6qVRyQqR6qCd8OAXR340wpz8NsYFW22I5fby0uGCGy8m/iZDVBTrE3vZkI3yqJEtu3c7wjOjst0fUd7hj2wqDHP2c=
  - secure: KwMj3AgniM5QmOEpM83HTVJ1PulEZuCpx2j5Bu3h5BxjlWh+qRVcvo9KPRnapiE2A37RvzVQJYLRoTf3+HjJVnrChGpFBpyGtbNKTJwMvp/w0NJyhR33rqJxpSsUoypYEys+Izo0AbCYTLo9gF9c6YMvpTMe6/6BELZJNdVxqRU=
  - secure: l6yPCNygR3kAyM1bPVj3DWGKpMJkX4xzh3/DBIGPd4nYX3yjTnxvcc4OyeWy8+a/NbFWvs4AQS95gNue5xHwm93Y+GfFS2D5ktd6nASiT83HFBax8s24SPsUVvLuyGxBcoEZQOvPMWWRFqTljkB/uxLdg+d5uAVsJhqPYhaQccc=
  - secure: KY97iUoeQPsyZPpweZtahAidoEumS2pgsslkv0p89j8G0aHySzm/mzRByGAwGCoSG6sojSFDYYuKC5JmiFqxFZyY2KKbWiaIAr+YGF3MlLG2qlAhKfqwqY/wizf8C8xyy3jhYaoAzq0nTMphuayinIaO3e79IPe2LvDRSvYhBus=
  - secure: carhyMFtS16L0vmZLk6gQ2fsk251Da6epi1CZFe6cznnYdNIMVKAEHuFoK7JAKX/hdYBgnRERbmc0bTvNFlGLi4Vg0Wt0BZoHDy9OmkOniy6xdBAoPyX8yZwq6IIjVL7JWsTp27RT9JzN1QRrlcZl9+7Ob42rUrjaS9ap/CklJ8=
  - secure: QGb1HiWu0FpGiluqzEiYyDytFNH/oZ5IOmHtpL4Mh9LKnm4BegaS3iAQ7AZMDMiaQf3cX1uh/lBd3Q9zVTuFg6fOK8nce+bRGFnx4zWlnLjz8HA9266uWrbW70TS+JpWK19ahKfyDL4VLSa4PrNm2F9dFuzGa9cDG1hWWjcM4+o=
  - secure: e/LyZCwyD9m9W2vb1hrdxajgeta6XX+ttT23Hdv89o/fGAT6Pyhrp01rnp9wgCQasUz2MYwPqCybA9mQvRXw9S5W6f6tRSLWEUQtfjq9p9qIJizVx5iuaZYGG7y93VXg5K1R5VErj08rim1Z8Baenbh3TZ/LDk0967jG9bJSzCE=
  - secure: NiI2pnYjGQif4TxOoMYKQEv2Dq7ATEjXwKOOUnqOSqjSFg/GVpHcg3uZQ8THl2o8cNx6V5Qw/skyGL2p94sb6nilYbV4rkQzRyRBwx5cSsc/EKE1TLpmNn/3P2teTjI3cefPtcGcbn6UZMFruP9UD9SLoP2D2lxGxaSUCGxv6sI=
  - secure: ibZCQnE6TGYgTsTLC5O77ClwF/lkWRWdYEiR/YBobkM16emcpL/ADkknNJj2RkMNqtyi9LBgBE2utKzgrnTwizQtMKwBMtCqf691iui7hNkAhylXtV2zXVSXvGVjQEibj30cvaQkWDRUPcs1q5txiMbbIS/Q6cEBeGnZnS76WeE=
  - secure: UiWIBGyrIhKrHRRMYZNK6QgI4a7ip4jLqxaFu2gJC7BYh2rSC35X0Awj8vcjmxri2uiY2PjxYNI41OaE6QtER0wSQs0Ka8oue08bJRHclvCLVWeQ4+DN3+bDlHCocxXpQCJUCV4h3yoQ6n/WEGANS+iz2mvFYMpvf5Zt4L6iX7M=
  - secure: lhW2tmHdDNoFRg3F01YX4zKbvuDU06Mn/EZsHsJAdfkbItb59Hvht7BTD+1GUt9/z3aq9wox5Lo4JEZ3bg9P5BKNzGWo91twV2fkJOg+QPJImsrlYDSmiCohzj1Gca1r8FPFMbx1mULT/+agBxvWMj/zSHsuDh1FeEw9RCf3M44=
  - secure: Q76PtYvw187XO2yjpKncTwwLhuj7tMMEnYFckz6vGqZHCMpti0A8e10fX1sol98ga9tvc3XKhOTAD79XDdTDT8dcNaq7rtxMGtga4tF/CzXK012Y1UNyfDuw6cNcRC0SJ4Hjzs2dhkkYQPSEuREHU1oFeDhd35UKpQU3im30tL8=
  - secure: Q44/AwfmAk8cPJM1Ar1vMM2sAZSH2hIyqD7rPKiXiuNMYckoO0HXHIwdNN95h4DgBjVPS2waMkuSF7Fi7Ewto9dsJ+UZEW4j62r+ai48V082r7bfnN0Ak8L+28NEALTfh2vn7D2X0lUo9n0zle4KUIIBcGu8oMNkzbOp4zN9qbM=
  - secure: PTowiE8JnfInf7C1ow1BngK4Gl15bofSo1qckPXluJeN3BgtY3PYqawuLn7YB9V0RytWfxMrLYzJKjDiiIhuyupJXQKBaSAkqXf8WbutHdEBMmU6cqh2NKaXe+RjNgO7crysVsNQOeHNW+DItipiQby8MhygGxg0USPziM2PSGk=
  - secure: jaBoIX9tGQs+pbjjSekcseCzWgoUY5fUkTOElz3G2Yc9WD+ZYX3oSaqlw/ov4QxBuAMTxXwvvu84GC4LyiEXOWUAfZgSxhNsCM3yNrt3qJCdBTi0iSVng6GA8P3jadCPlEFMZOX7LWcsB2cC/1PKXDSAI5t4eNQlbs/qXrYtfUg=
  - secure: TXcc0JkLDJ9VuQk6wqrAHn5Tq3nPkAqmE+dM+p9mtGypfabrYrBmtMgAriPE8V80dTfPE9uwutKQLC3+G7F0kGH6TmOGVDe7iKugjBfVlNwIRr6XLj2yJaIwm+8f6WH8OLR5dqlmJFMyQzm964Vh7qEBtp+tY0cekYH6wn2TuAc=
  - secure: Idx1SbcF/HSsjPT9wvDpgA1PTFrfQ+9EqvZkzN4qf5i6TpdAkY838X25uVzF74xgxMZ9HFArh7tADDQjDcpE7vpBdb6kBcSomeJh7alxx4qpGsot7OXIbADwI6DflaJ75gdV4qCS5D+8WFQ/U3G41gFgCQKCrDkauHsyIQmJgkM=
  - secure: DiOr8nL5p036Pgq764xyxYimnC/mtOo+Jur/Sh9lp98/DwdHHhF2ByAZwTwIIwpeIzyOT3JRt1Fe6BCQ7dLHE6eHFGCb1r4omPnWZ4ZXQlh5ePY4aF1LeUPn5TYmljdouEmmzk/ZO3+ZueGjhgPI+9SlvOTglvZvI5JjebMjb54=
  - secure: JeBR0qLN8eroHcPkf3OfeIDroynF48F3xIFTzFv1RE3UGwKfpRfbi+OsCCfhwmVnze88VwVUQpuLkMsIA3Kzn1k34/opaF2rs9m1OeM8dcSH+YMUf383hJ2cU4gwfAVA49oLS3Vq8yDFF4RP48atRysPFEwFEft2wuSPPo8F/kM=
  - secure: bFOB6tt1u97mbqc2pMqPoXvIYvWII+TRujoHzMhJBPt29cQ9hoZJiC0x7EMEgG4jr0TsOPZrLmHLAnenLAM2TIoV5305PUwbPwaXVZMHufv6n3f/1LF9pRSbIUktLt5IUHR9ouutqUH7Ik7VbktS/kgAvh5oroD8/9PgCTJO9T0=
  - secure: RuTKET3KweSeZMMK+HC2aEOTH4fs7vM1RCt8HqAegCBEHLiW2Nvva2+IE5o+7NR3p1ZNAFK7Vix/yzam9pC6c95FiyUxMi3tbW0TUviqPueEx80xHA8XcMoCbTbLoiwwPGhGGqVA6kfCBAp/NzeIsPEC25edzqv6U8iBIT9SuzM=
  - secure: LvaZARRMrXkkCV4JzSInchfXourl9Bh92kIhYB0ezhdiZMIztzSa5seJByvMoRpldjEcG7713bx+Q+LWZn/yDlCSz5Cf19PLdIkeMD2N5A6ZVLRsmbV6OcrdpxcCBEttsyOQkDmd3GuPkSnqU4Q5NgyibfzUWZf2D5ZdKS+z8pY=
  - secure: aGkaI0nSh9dctcFC6ZmBDP4G7jxfVZb/J86V9nLhh3uSQMU0MZb1NHuyklzBr2gymtRIMe6eeqO4sksazGS8j1USezslYCQBBkN/3kymSkjB9ISGKKqveTCddfZ31JTNzfN4VtU8jMdHfFkolkv70F51g0fGba/6RquNRyK9g2o=
  - secure: fL4mRXDiQMX+2rKzDl/5+Nl385uPklLfb9XXzcl1XPuKvWUzgIywX6fBEXLMXJaDczBZVPalVKuR6YCQR8zzsC1uKToAYTp6zye2jxv/KqPKQoIm5A24lC0ttx+Rt/ZNsEUG60MXL2GuYTcZLaSOdZy/3mnldaYd9LDwqnJH4EY=
  - secure: ezbU8rsikA4tvQlh8gjnVmhvxYlUKWXECSZIt49iSj9HxS44TibF3nAIrfxtvO9oMWZO+Mf38WwIclzQAsIE2ZvA5tKHFDtZI82So8O78Pn++7960dbTONovxLVwfscnx71d3IP+Lv6EbVa/tiQI2rz6hN4pk8mlKQW/Su5j/SE=
  - secure: RUxUaTMJLQM2njfqcq3sc35CpCpB1FHL7+ilZxp0BioNjONfoS3sYaabepMJl8SLWCiw/0dAyoYlXrQR+suDVkELZEQbjI0BKJ8YFkaFHwQ5OrBGNglB1iquuZfeiACa4JsuLhRXLG22SJmhajBTSa7eJLlxBCIAwjDh5K/aqAs=
  - secure: Lv1kDByX5csAPzYbwK/3WNVKaJTPAtvfc5A0ebGtueRhNwu1yGx3Zk77x0cZ51Y71F6fIOKCrYbrBbWWtihFnmvIH6EvCbHt/47pi9/5zxtqXrKtQ5Jas+rl5RZ0XAcloCW/EuCaTx6ya/0JLp8AAKxfkI/Mgwh44M8e1SXDm5Y=
  - secure: n51H8IQ/3uCvcr/Kjj6mbHkOL2pjCxV4KU7DMJ/f906ERGStRsaiwa1TnIGB46oDVHfIyrq2RnuShqKYOZgJdYMRMldZqOzyIsODQY5z4qbRCsXMpyi7Hd80D1A1nn09VnchlbfcQfypJDc/0aJHh3tzRQvfPpnsG44sIKxNijY=
  - secure: SssvEJF6+OAbMLpIM37WWkzxubjmwQKe6kYlM8Ind94CxIQxGRM63cX70O1Ir4HCJfPWawmqZRwT77iXynCtSSgjtyXnE1g7pkOxGj8i7/G5WROcs4EFEnI3C0knQZfi4tC7Y+YtUpKyAGMgu6Gz4BjtSFo6D5vKZ42G5dvIuWg=
  - secure: RmgJCY/wt8l09GQU73keyMmue0eW2wkNqfYMqa2mzhYwLGXJVtVJxCNWJhBLZRTlb3IRYBsE8eqBkmQWNbzm0A4bet/l/XLjUaJov8+kX+dNXhmhrv1j8Ms7jI9fDIc+atVnEEFWVaGxzi4USvk06jUFyv7jFz95+QbIbvMOfkI=
  - secure: k5ptrfb+y7NFC98hoakmoMv5G6xNYeHulNpwCWr7F0jtf9uFUVJaVSxBl2lvqhPdA6Vis09RJxgj37Zpf8zCC+iX2COMv9u7Ua90VvnWKbV5F9tCD0v0S99FupjfZ96tj8nJdL0Hyh0FV3kPeTkQ/1Lh3Ng7RufUdp/kaElr6rc=
  - secure: jf8fAo/ZVr41G6LKKjlilD15T9qMpfYkg84aGF5llCCKLS25FmRmZRcO92BA3y87FGAEsrT3HGcCZ/WjPmWlPRiKJVMWdqhqyXdsDe8m+8hJf/m7asOY6JG/ly4WLCw6n9cTEta5y0wdAhvlZw+zZIotc6hui+MHy3xzY9IeAsQ=
  - secure: JRZAihDLBhnA7ahvBoojcHwIDktfVNN4dlXLRS8Syk5HNjLEJeeqfZIrab6ltfQfO2+xFfxAcLk7DN87gakBpTWIMQRNpI9jClgeczuI3X0zeJUX+Ln1tpJNfMp2FEuU/fbZ7eBe0eL+/GS35rbR7plXegUwD1UAM6jrLil1yXg=
  - secure: JBAtRKdd/ok1ToedHIWsEa1k6d4cqxH7vrC9xRj5w0NEGMyDQbNeSBkdFqgB9mfYNN8ztO0RbIxpW4NT6mPOGwkA3UTOGDdI25ZZQB7EjFXm4iWwzSGKPJ1evRWeFIvPD5BJeoyayHEUY+s7ghttDcWIMkmL33jc/u/BUdkIBPw=
  - secure: DfWI9zb7Ni4xkVvgdWDHajDNy/ksV5QSv/yfFjX4kSwE86GFlWuLRzHP6BIN+GLZpS3VIZyPKlg9XbzQiKl3HYnau3qAPjQIc5JiDOMbyiy/VwG3dHnP0h+JFqBc85JwUOPvcVRBFx3VHdJTjMordRSM0fQ67nTPiz1g0Fj340g=
  matrix:
  - KITCHEN_INSTANCE='default-ubuntu-1204'
  - KITCHEN_INSTANCE='default-ubuntu-1004'
  - KITCHEN_INSTANCE='default-centos-64'
  - KITCHEN_INSTANCE='default-centos-53'
  - KITCHEN_INSTANCE='deploy-libs-ubuntu-1204'
  - KITCHEN_INSTANCE='deploy-libs-ubuntu-1004'
  - KITCHEN_INSTANCE='deploy-libs-centos-64'
  - KITCHEN_INSTANCE='deploy-libs-centos-53'
  - KITCHEN_INSTANCE='deploy-war-ubuntu-1204'
  - KITCHEN_INSTANCE='deploy-war-ubuntu-1004'
  - KITCHEN_INSTANCE='deploy-war-centos-64'
  - KITCHEN_INSTANCE='deploy-war-centos-53'
script:
- bundle exec kitchen test $KITCHEN_INSTANCE
after_script:
- bundle exec kitchen destroy $KITCHEN_INSTANCE
notifications:
  email:
  - aivantsov@qubell.com
